/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital.gui;

import hospital.dbutil.DBconnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class PatientHistory extends javax.swing.JFrame {
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    /**
     * Creates new form PatientHistory
     */
    public PatientHistory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        patidtxt = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fnametxt = new javax.swing.JTextField();
        agetxt = new javax.swing.JTextField();
        gendertxt = new javax.swing.JTextField();
        maritaltxt = new javax.swing.JTextField();
        visitdatetxt = new javax.swing.JTextField();
        visittimetxt = new javax.swing.JTextField();
        lnametxt = new javax.swing.JTextField();
        bloodgrptxt = new javax.swing.JTextField();
        phtxt = new javax.swing.JTextField();
        pattypetxt = new javax.swing.JTextField();
        bednotxt = new javax.swing.JTextField();
        desctxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        diseasetxt = new javax.swing.JTextField();
        tab1txt = new javax.swing.JTextField();
        tab2txt = new javax.swing.JTextField();
        tab3txt = new javax.swing.JTextField();
        tab4txt = new javax.swing.JTextField();
        dose1txt = new javax.swing.JTextField();
        dose2txt = new javax.swing.JTextField();
        dose3txt = new javax.swing.JTextField();
        dose4txt = new javax.swing.JTextField();
        effecttxt = new javax.swing.JTextField();
        daystxt = new javax.swing.JTextField();
        addrtxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home page.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 255));
        jLabel2.setText("CHECK PATIENT HISTORY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(452, 452, 452)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1340, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PATIENT ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 150, 80));
        getContentPane().add(patidtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 380, -1));

        searchbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchbtn.setForeground(new java.awt.Color(102, 0, 255));
        searchbtn.setText("SEARCH");
        searchbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 150, 110, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("================================================Patient Details========================================");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, 1158, -1));

        fnametxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fnametxt.setBorder(null);
        jPanel2.add(fnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 64, 154, 30));

        agetxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        agetxt.setBorder(null);
        jPanel2.add(agetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 105, 154, 30));

        gendertxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gendertxt.setBorder(null);
        jPanel2.add(gendertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 146, 154, 30));

        maritaltxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        maritaltxt.setBorder(null);
        jPanel2.add(maritaltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 187, 154, 30));

        visitdatetxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        visitdatetxt.setBorder(null);
        jPanel2.add(visitdatetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 228, 154, 30));

        visittimetxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        visittimetxt.setBorder(null);
        jPanel2.add(visittimetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 269, 154, 30));

        lnametxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lnametxt.setBorder(null);
        jPanel2.add(lnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 64, 154, 30));

        bloodgrptxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bloodgrptxt.setBorder(null);
        jPanel2.add(bloodgrptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 105, 154, 30));

        phtxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phtxt.setBorder(null);
        jPanel2.add(phtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 150, 154, 30));

        pattypetxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pattypetxt.setBorder(null);
        jPanel2.add(pattypetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 191, 154, 30));

        bednotxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bednotxt.setBorder(null);
        jPanel2.add(bednotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 235, 154, 30));

        desctxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        desctxt.setBorder(null);
        jPanel2.add(desctxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 276, 154, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("=================================================================Hospital Management System==============");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 384, 1168, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("================================Prescription==========================");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 68, 662, -1));

        diseasetxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        diseasetxt.setBorder(null);
        jPanel2.add(diseasetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 114, 290, 30));

        tab1txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tab1txt.setBorder(null);
        jPanel2.add(tab1txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 150, 138, 30));

        tab2txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tab2txt.setBorder(null);
        tab2txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab2txtActionPerformed(evt);
            }
        });
        jPanel2.add(tab2txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 191, 138, 30));

        tab3txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tab3txt.setBorder(null);
        jPanel2.add(tab3txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 235, 138, 30));

        tab4txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tab4txt.setBorder(null);
        jPanel2.add(tab4txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 276, 138, 30));

        dose1txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dose1txt.setBorder(null);
        jPanel2.add(dose1txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 140, 30));

        dose2txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dose2txt.setBorder(null);
        jPanel2.add(dose2txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 140, 30));

        dose3txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dose3txt.setBorder(null);
        jPanel2.add(dose3txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, 140, 30));

        dose4txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dose4txt.setBorder(null);
        jPanel2.add(dose4txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 270, 140, 30));

        effecttxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        effecttxt.setBorder(null);
        jPanel2.add(effecttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 300, 30));

        daystxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        daystxt.setBorder(null);
        jPanel2.add(daystxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 110, 70, 30));

        addrtxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addrtxt.setBorder(null);
        jPanel2.add(addrtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 340, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 20, 300));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 1080, 420));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Background img.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PatientDetails d = new PatientDetails();
        d.show();
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        try
        {
        con = DBconnection.getConnection();
        pst=(PreparedStatement)con.prepareStatement("select pat_id,pat_fname,pat_lname,pat_age,pat_bloodgrp,pat_gender,pat_ph,pat_marital,pat_patype,pat_visitdate,pat_disease,pat_patype,pat_bedno,pat_visittime,pat_addr,prs_disease,prs_tab1,prs_dose1,prs_tab2,prs_dose2,prs_tab3,prs_dose3,prs_tab4,prs_dose4,prs_sideeffect,prs_days from patient1,prescription where patient1.pat_id = prescription.prs_patid and patient1.pat_id = ?");
        String id=patidtxt.getText();
        //int id=Integer.parseInt(patidtxt.getText());
        pst.setString(1, id);
        //pst.setInt(1, id);
        ResultSet rs1=pst.executeQuery();
        if(rs1.next()==false)
        {
        JOptionPane.showMessageDialog(this,"No Data Found");
        diseasetxt.setText("");
        tab1txt.setText("");
        dose1txt.setText("");
        tab2txt.setText("");
        dose2txt.setText("");
        tab3txt.setText("");
        dose3txt.setText("");
        tab4txt.setText("");
        dose4txt.setText("");
        effecttxt.setText("");
        daystxt.setText("");
        patidtxt.setText("");
        fnametxt.setText("");
        lnametxt.setText("");
        bloodgrptxt.setText("");
        phtxt.setText("");
        pattypetxt.setText("");
        visitdatetxt.setText("");
        desctxt.setText("");
        gendertxt.setText("");
        maritaltxt.setText("");
        agetxt.setText("");
        }
        else
        {
        patidtxt.setText(rs1.getString("pat_id"));
        fnametxt.setText(rs1.getString("pat_fname"));
        lnametxt.setText(rs1.getString("pat_lname"));
        agetxt.setText(rs1.getString("pat_age"));
        phtxt.setText(rs1.getString("pat_ph"));
        bloodgrptxt.setText(rs1.getString("pat_bloodgrp"));
        pattypetxt.setText(rs1.getString("pat_patype"));
        visitdatetxt.setText(rs1.getString("pat_visitdate"));
        desctxt.setText(rs1.getString("pat_disease"));
        diseasetxt.setText(rs1.getString("prs_disease"));
        tab1txt.setText(rs1.getString("prs_tab1"));
        dose1txt.setText(rs1.getString("prs_dose1"));
        tab2txt.setText(rs1.getString("prs_tab2"));
        dose2txt.setText(rs1.getString("prs_dose2"));
        tab3txt.setText(rs1.getString("prs_tab3"));
        dose3txt.setText(rs1.getString("prs_dose3"));
        tab4txt.setText(rs1.getString("prs_tab4"));
        dose4txt.setText(rs1.getString("prs_dose4"));
        effecttxt.setText(rs1.getString("prs_sideeffect"));
        daystxt.setText(rs1.getString("prs_days"));
        gendertxt.setText(rs1.getString("pat_gender"));
        maritaltxt.setText(rs1.getString("pat_marital"));
        visittimetxt.setText(rs1.getString("pat_visittime"));
        addrtxt.setText(rs1.getString("pat_addr"));
        bednotxt.setText(rs1.getString("pat_bedno"));
        
        /*String sex = rs1.getString("pat_gender");
       if(sex.equals("Male"))
       {
           gendertxt.setText(rs1.getString("pat_gender"));
           //malerb.setSelected(true);
       }
       else if(sex.equals("Female"))
       {
           gendertxt.setText(rs1.getString("pat_gender"));
           //femalerb.setSelected(true);
       }
       else
       {
           gendertxt.setText(rs1.getString("pat_gender"));
           //otherrb.setSelected(true);
       }
       
       /*String marriage = rs1.getString("pat_marital");
       if(marriage.equals("Single"))
       {
           singlerb.setSelected(true);
       }
       else
       {
           marriedrb.setSelected(true);
       }*/
        }
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,"DB Error"+ex,"Exception",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
        catch(Exception e)
        {
        e.printStackTrace();
        }
        
    }//GEN-LAST:event_searchbtnActionPerformed

    private void tab2txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab2txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tab2txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addrtxt;
    private javax.swing.JTextField agetxt;
    private javax.swing.JTextField bednotxt;
    private javax.swing.JTextField bloodgrptxt;
    private javax.swing.JTextField daystxt;
    private javax.swing.JTextField desctxt;
    private javax.swing.JTextField diseasetxt;
    private javax.swing.JTextField dose1txt;
    private javax.swing.JTextField dose2txt;
    private javax.swing.JTextField dose3txt;
    private javax.swing.JTextField dose4txt;
    private javax.swing.JTextField effecttxt;
    private javax.swing.JTextField fnametxt;
    private javax.swing.JTextField gendertxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lnametxt;
    private javax.swing.JTextField maritaltxt;
    private javax.swing.JTextField patidtxt;
    private javax.swing.JTextField pattypetxt;
    private javax.swing.JTextField phtxt;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField tab1txt;
    private javax.swing.JTextField tab2txt;
    private javax.swing.JTextField tab3txt;
    private javax.swing.JTextField tab4txt;
    private javax.swing.JTextField visitdatetxt;
    private javax.swing.JTextField visittimetxt;
    // End of variables declaration//GEN-END:variables
}
