/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital.gui;
/**
 *
 * @author Kaustubh
 */
public class PatientPortal extends javax.swing.JFrame {
    String nm;
    

    /**
     * Creates new form PatientPortal
     */
    public PatientPortal() {
        initComponents();
    }
    public PatientPortal(String name) {
        initComponents();
        nm = name;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkdetailsbtn = new javax.swing.JButton();
        chkaptbtn = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chkdetailsbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chkdetailsbtn.setForeground(new java.awt.Color(255, 0, 255));
        chkdetailsbtn.setText("CHECK YOUR DETAILS");
        chkdetailsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkdetailsbtnActionPerformed(evt);
            }
        });
        getContentPane().add(chkdetailsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 340, 260, 90));

        chkaptbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chkaptbtn.setForeground(new java.awt.Color(255, 0, 255));
        chkaptbtn.setText("CHECK APPOINTMENTS");
        chkaptbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkaptbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                chkaptbtnMouseEntered(evt);
            }
        });
        chkaptbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkaptbtnActionPerformed(evt);
            }
        });
        getContentPane().add(chkaptbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 260, 90));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SELECT AN OPTION:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 400, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_patientPortal/pngaaa.com-1107109.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 420, 340));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 255));
        jLabel2.setText("PATIENT PORTAL");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 440, 50));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home page.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 10, 70, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1440, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images_patientPortal/1440,720_bg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1918, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chkaptbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkaptbtnActionPerformed
        // TODO add your handling code here:
        Appointments ap = new Appointments(nm);
        ap.show();
        
        dispose();
    }//GEN-LAST:event_chkaptbtnActionPerformed

    private void chkdetailsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkdetailsbtnActionPerformed
       PatientPortal_CheckDetails pd = new PatientPortal_CheckDetails(nm);
       pd.show();
       
       dispose();
    }//GEN-LAST:event_chkdetailsbtnActionPerformed

    private void chkaptbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkaptbtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_chkaptbtnMouseClicked

    private void chkaptbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkaptbtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_chkaptbtnMouseEntered

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Patient_login_real plr = new Patient_login_real();
        plr.show();
        
        dispose();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton chkaptbtn;
    private javax.swing.JButton chkdetailsbtn;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
