/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.gui;

import hospital.dbutil.DBconnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class StaffPortal_chngpwd extends javax.swing.JFrame {
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    Statement st;

    /**
     * Creates new form StaffPortal_chngpwd
     */
    public StaffPortal_chngpwd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        oldpwdtxt = new javax.swing.JTextField();
        newpwdtxt = new javax.swing.JTextField();
        conpwdtxt = new javax.swing.JTextField();
        changebtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        lblid = new javax.swing.JLabel();
        lblold = new javax.swing.JLabel();
        lblcon = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Change");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 54, -1, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User Id :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 80, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Old Password :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("New Password :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Confirm Password :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));
        jPanel1.add(idtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 190, -1));
        jPanel1.add(oldpwdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 190, -1));
        jPanel1.add(newpwdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 190, -1));
        jPanel1.add(conpwdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 190, -1));

        changebtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        changebtn.setText("Change");
        changebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changebtnActionPerformed(evt);
            }
        });
        jPanel1.add(changebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 80, 40));

        clearbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });
        jPanel1.add(clearbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 80, 40));

        lblid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblid.setForeground(new java.awt.Color(51, 255, 255));
        jPanel1.add(lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        lblold.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblold.setForeground(new java.awt.Color(51, 255, 255));
        jPanel1.add(lblold, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        lblcon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblcon.setForeground(new java.awt.Color(51, 255, 255));
        jPanel1.add(lblcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small_window bg.jpg"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void changebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changebtnActionPerformed
        // TODO add your handling code here:
        String uname=idtxt.getText();
        String strpass=oldpwdtxt.getText();
        String newpass=newpwdtxt.getText();
        String conpass=conpwdtxt.getText();
        try
        {
            
            con = DBconnection.getConnection();
            st = con.createStatement();
            rs = st.executeQuery("select * from adminname");
            while(rs.next())
            {
                String usrname = rs.getString("username");
                String passwd = rs.getString("password");
                if(uname.equals(usrname) && strpass.equals(passwd))
                {

                if(newpass.equals(conpass))
                {
                    con = DBconnection.getConnection();
                    pst=(PreparedStatement)con.prepareStatement("update adminname set password=? where username=?");
                    pst.setString(1,newpass);
                    pst.setString(2,uname);
                    pst.executeUpdate();
       
                   // Statement st1 = con.createStatement();
                   // st1.executeUpdate("UPDATE adminname SET password='newpass' where username='uname' ");//query i am using to update the password
                    JOptionPane.showMessageDialog(null, "PASSWORD UPDATE SUCCESSFUL");
                    idtxt.setText("");
                    oldpwdtxt.setText("");
                    newpwdtxt.setText("");
                    conpwdtxt.setText("");
                }

                else
                {
                    JOptionPane.showMessageDialog(null, "PLEASE CONFIRM PASSWORD");
                }
                }
            else if(uname.equals("") && strpass.equals("") && newpass.equals(""))
            {
                JOptionPane.showMessageDialog(null, "PLEASE ENTER ALL INFORMATION");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "USERNAME NOT FOUND");
            }
                
        }
           

    }
            catch(Exception e)
            {
                e.printStackTrace();
            } 
    }//GEN-LAST:event_changebtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        // TODO add your handling code here:
        idtxt.setText("");
        oldpwdtxt.setText("");
        newpwdtxt.setText("");
        conpwdtxt.setText("");
    }//GEN-LAST:event_clearbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffPortal_chngpwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffPortal_chngpwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffPortal_chngpwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffPortal_chngpwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffPortal_chngpwd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton changebtn;
    private javax.swing.JButton clearbtn;
    private javax.swing.JTextField conpwdtxt;
    private javax.swing.JTextField idtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcon;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblold;
    private javax.swing.JTextField newpwdtxt;
    private javax.swing.JTextField oldpwdtxt;
    // End of variables declaration//GEN-END:variables
}
